Version: "1.0.0"
Enabled: true
Allow-NonOomph-Conn: false

# Prefix for Oomph.
Prefix: "§7§l[§eoomph§7]§r"
# Message that is broadcast to staff, alerting them that a player failed a check.
FlaggedMessage: "{prefix} §d{player} §7flagged §4{check_main} §7(§c{check_sub}§7) §7[§5x{violations}§7]"

# Message that is used for the logs command when the player does not have any logs.
NoLogMessage: "{prefix} §a{player} has no existing logs."
# Message that is used for the logs command when the player has existing logs.
StartLogMessage: "{prefix} §5Log summary for §d{player}:"
LogMessage: "§7- §5{check_main}§7<§d{check_sub}§7> §7[§cx{violations}§7]"